/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ACommaAssign extends PCommaAssign
{
    private TId _id_;
    private final LinkedList _assignV_ = new TypedLinkedList(new AssignV_Cast());

    public ACommaAssign()
    {
    }

    public ACommaAssign(
        TId _id_,
        List _assignV_)
    {
        setId(_id_);

        {
            this._assignV_.clear();
            this._assignV_.addAll(_assignV_);
        }

    }
    public Object clone()
    {
        return new ACommaAssign(
            (TId) cloneNode(_id_),
            cloneList(_assignV_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaAssign(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getAssignV()
    {
        return _assignV_;
    }

    public void setAssignV(List list)
    {
        _assignV_.clear();
        _assignV_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_assignV_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_assignV_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _assignV_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AssignV_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAssignV node = (PAssignV) o;

            if((node.parent() != null) &&
                (node.parent() != ACommaAssign.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACommaAssign.this))
            {
                node.parent(ACommaAssign.this);
            }

            return node;
        }
    }
}
