/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AForStatement extends PStatement
{
    private TId _forid_;
    private TId _inid_;
    private PStatement _statement_;

    public AForStatement()
    {
    }

    public AForStatement(
        TId _forid_,
        TId _inid_,
        PStatement _statement_)
    {
        setForid(_forid_);

        setInid(_inid_);

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AForStatement(
            (TId) cloneNode(_forid_),
            (TId) cloneNode(_inid_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStatement(this);
    }

    public TId getForid()
    {
        return _forid_;
    }

    public void setForid(TId node)
    {
        if(_forid_ != null)
        {
            _forid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _forid_ = node;
    }

    public TId getInid()
    {
        return _inid_;
    }

    public void setInid(TId node)
    {
        if(_inid_ != null)
        {
            _inid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inid_ = node;
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_forid_)
            + toString(_inid_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_forid_ == child)
        {
            _forid_ = null;
            return;
        }

        if(_inid_ == child)
        {
            _inid_ = null;
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_forid_ == oldChild)
        {
            setForid((TId) newChild);
            return;
        }

        if(_inid_ == oldChild)
        {
            setInid((TId) newChild);
            return;
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }
}
