/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AIfStatement extends PStatement
{
    private PComparisonOr _comparisonOr_;
    private PStatement _statement_;

    public AIfStatement()
    {
    }

    public AIfStatement(
        PComparisonOr _comparisonOr_,
        PStatement _statement_)
    {
        setComparisonOr(_comparisonOr_);

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AIfStatement(
            (PComparisonOr) cloneNode(_comparisonOr_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStatement(this);
    }

    public PComparisonOr getComparisonOr()
    {
        return _comparisonOr_;
    }

    public void setComparisonOr(PComparisonOr node)
    {
        if(_comparisonOr_ != null)
        {
            _comparisonOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonOr_ = node;
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonOr_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_comparisonOr_ == child)
        {
            _comparisonOr_ = null;
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonOr_ == oldChild)
        {
            setComparisonOr((PComparisonOr) newChild);
            return;
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }
}
