/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListStatement extends PStatement
{
    private TId _id_;
    private PExpression _lbr_;
    private PExpression _rbr_;

    public AListStatement()
    {
    }

    public AListStatement(
        TId _id_,
        PExpression _lbr_,
        PExpression _rbr_)
    {
        setId(_id_);

        setLbr(_lbr_);

        setRbr(_rbr_);

    }
    public Object clone()
    {
        return new AListStatement(
            (TId) cloneNode(_id_),
            (PExpression) cloneNode(_lbr_),
            (PExpression) cloneNode(_rbr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListStatement(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PExpression getLbr()
    {
        return _lbr_;
    }

    public void setLbr(PExpression node)
    {
        if(_lbr_ != null)
        {
            _lbr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lbr_ = node;
    }

    public PExpression getRbr()
    {
        return _rbr_;
    }

    public void setRbr(PExpression node)
    {
        if(_rbr_ != null)
        {
            _rbr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rbr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_lbr_)
            + toString(_rbr_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_lbr_ == child)
        {
            _lbr_ = null;
            return;
        }

        if(_rbr_ == child)
        {
            _rbr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_lbr_ == oldChild)
        {
            setLbr((PExpression) newChild);
            return;
        }

        if(_rbr_ == oldChild)
        {
            setRbr((PExpression) newChild);
            return;
        }

    }
}
