/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListConExpression extends PExpression
{
    private TLBr _lBr_;
    private PExpression _expression_;
    private final LinkedList _commaExp_ = new TypedLinkedList(new CommaExp_Cast());

    public AListConExpression()
    {
    }

    public AListConExpression(
        TLBr _lBr_,
        PExpression _expression_,
        List _commaExp_)
    {
        setLBr(_lBr_);

        setExpression(_expression_);

        {
            this._commaExp_.clear();
            this._commaExp_.addAll(_commaExp_);
        }

    }
    public Object clone()
    {
        return new AListConExpression(
            (TLBr) cloneNode(_lBr_),
            (PExpression) cloneNode(_expression_),
            cloneList(_commaExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListConExpression(this);
    }

    public TLBr getLBr()
    {
        return _lBr_;
    }

    public void setLBr(TLBr node)
    {
        if(_lBr_ != null)
        {
            _lBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBr_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getCommaExp()
    {
        return _commaExp_;
    }

    public void setCommaExp(List list)
    {
        _commaExp_.clear();
        _commaExp_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_lBr_)
            + toString(_expression_)
            + toString(_commaExp_);
    }

    void removeChild(Node child)
    {
        if(_lBr_ == child)
        {
            _lBr_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_commaExp_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBr_ == oldChild)
        {
            setLBr((TLBr) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _commaExp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaExp_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaExp node = (PCommaExp) o;

            if((node.parent() != null) &&
                (node.parent() != AListConExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AListConExpression.this))
            {
                node.parent(AListConExpression.this);
            }

            return node;
        }
    }
}
