/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMaxExpression extends PExpression
{
    private PValue _value_;
    private final LinkedList _commaV_ = new TypedLinkedList(new CommaV_Cast());

    public AMaxExpression()
    {
    }

    public AMaxExpression(
        PValue _value_,
        List _commaV_)
    {
        setValue(_value_);

        {
            this._commaV_.clear();
            this._commaV_.addAll(_commaV_);
        }

    }
    public Object clone()
    {
        return new AMaxExpression(
            (PValue) cloneNode(_value_),
            cloneList(_commaV_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaxExpression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getCommaV()
    {
        return _commaV_;
    }

    public void setCommaV(List list)
    {
        _commaV_.clear();
        _commaV_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_commaV_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_commaV_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _commaV_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaV_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaV node = (PCommaV) o;

            if((node.parent() != null) &&
                (node.parent() != AMaxExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMaxExpression.this))
            {
                node.parent(AMaxExpression.this);
            }

            return node;
        }
    }
}
