/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANotComparisonOr extends PComparisonOr
{
    private PComparisonOr _comparisonOr_;

    public ANotComparisonOr()
    {
    }

    public ANotComparisonOr(
        PComparisonOr _comparisonOr_)
    {
        setComparisonOr(_comparisonOr_);

    }
    public Object clone()
    {
        return new ANotComparisonOr(
            (PComparisonOr) cloneNode(_comparisonOr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotComparisonOr(this);
    }

    public PComparisonOr getComparisonOr()
    {
        return _comparisonOr_;
    }

    public void setComparisonOr(PComparisonOr node)
    {
        if(_comparisonOr_ != null)
        {
            _comparisonOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonOr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonOr_);
    }

    void removeChild(Node child)
    {
        if(_comparisonOr_ == child)
        {
            _comparisonOr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonOr_ == oldChild)
        {
            setComparisonOr((PComparisonOr) newChild);
            return;
        }

    }
}
