/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AOrComparisonOr extends PComparisonOr
{
    private PComparisonOr _lpar_;
    private PComparisonOr _rpar_;

    public AOrComparisonOr()
    {
    }

    public AOrComparisonOr(
        PComparisonOr _lpar_,
        PComparisonOr _rpar_)
    {
        setLpar(_lpar_);

        setRpar(_rpar_);

    }
    public Object clone()
    {
        return new AOrComparisonOr(
            (PComparisonOr) cloneNode(_lpar_),
            (PComparisonOr) cloneNode(_rpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrComparisonOr(this);
    }

    public PComparisonOr getLpar()
    {
        return _lpar_;
    }

    public void setLpar(PComparisonOr node)
    {
        if(_lpar_ != null)
        {
            _lpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lpar_ = node;
    }

    public PComparisonOr getRpar()
    {
        return _rpar_;
    }

    public void setRpar(PComparisonOr node)
    {
        if(_rpar_ != null)
        {
            _rpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rpar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lpar_)
            + toString(_rpar_);
    }

    void removeChild(Node child)
    {
        if(_lpar_ == child)
        {
            _lpar_ = null;
            return;
        }

        if(_rpar_ == child)
        {
            _rpar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lpar_ == oldChild)
        {
            setLpar((PComparisonOr) newChild);
            return;
        }

        if(_rpar_ == oldChild)
        {
            setRpar((PComparisonOr) newChild);
            return;
        }

    }
}
