/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TAssignDiv extends Token
{
    public TAssignDiv()
    {
        super.setText("/=");
    }

    public TAssignDiv(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAssignDiv(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAssignDiv(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAssignDiv text.");
    }
}
