/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TAssignMinus extends Token
{
    public TAssignMinus()
    {
        super.setText("-=");
    }

    public TAssignMinus(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAssignMinus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAssignMinus(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAssignMinus text.");
    }
}
