/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMultmult extends Token
{
    public TMultmult()
    {
        super.setText("**");
    }

    public TMultmult(int line, int pos)
    {
        super.setText("**");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMultmult(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMultmult(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMultmult text.");
    }
}
