/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(4), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(6), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(6), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(6), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(6), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(6), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(6), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(7), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(7), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(7), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(8), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(8), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(8), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(8), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(9), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(9), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(10), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(10), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(10), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(10), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(10), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(11), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(11), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(11), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(11), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(11), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(11), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(11), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(12), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(13), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(13), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(14), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(14), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(15), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(15), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(16), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(16), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(16), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(16), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(16), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(16), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(16), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(16), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(17), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(17), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(18), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(18), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(19), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(20), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(20), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(20), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(20), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(21), list);
		    }
		    break;


                    case 85:
		    {
			ArrayList list = new85();
			push(goTo(21), list);
		    }
		    break;


                    case 86:
		    {
			ArrayList list = new86();
			push(goTo(22), list);
		    }
		    break;


                    case 87:
		    {
			ArrayList list = new87();
			push(goTo(22), list);
		    }
		    break;


                    case 88:
		    {
			ArrayList list = new88();
			push(goTo(23), list);
		    }
		    break;


                    case 89:
		    {
			ArrayList list = new89();
			push(goTo(23), list);
		    }
		    break;


                    case 90:
		    {
			ArrayList list = new90();
			push(goTo(24), list);
		    }
		    break;


                    case 91:
		    {
			ArrayList list = new91();
			push(goTo(24), list);
		    }
		    break;


                    case 92:
		    {
			ArrayList list = new92();
			push(goTo(25), list);
		    }
		    break;


                    case 93:
		    {
			ArrayList list = new93();
			push(goTo(25), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new AGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new AGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFunCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFunction(tidNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        PArgument pargumentNode3;
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
	if(pargumentNode3 != null)
	{
	  listNode4.add(pargumentNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunction(tidNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }
        {
        }

        pargumentNode1 = new AArgument(tidNode2, listNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PAssignV passignvNode3;
        passignvNode3 = (PAssignV)nodeArrayList2.get(0);
	if(passignvNode3 != null)
	{
	  listNode4.add(passignvNode3);
	}
        }
        {
        }

        pargumentNode1 = new AArgument(tidNode2, listNode4, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, listNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode6 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PAssignV passignvNode3;
        passignvNode3 = (PAssignV)nodeArrayList2.get(0);
	if(passignvNode3 != null)
	{
	  listNode4.add(passignvNode3);
	}
        }
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, listNode4, listNode6);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaAssign pcommaassignNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        }

        pcommaassignNode1 = new ACommaAssign(tidNode2, listNode3);
        }
	nodeList.add(pcommaassignNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaAssign pcommaassignNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
        PAssignV passignvNode3;
        passignvNode3 = (PAssignV)nodeArrayList3.get(0);
	if(passignvNode3 != null)
	{
	  listNode4.add(passignvNode3);
	}
        }

        pcommaassignNode1 = new ACommaAssign(tidNode2, listNode4);
        }
	nodeList.add(pcommaassignNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignV passignvNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        passignvNode1 = new AAssignV(pvalueNode2);
        }
	nodeList.add(passignvNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PStatement pstatementNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonorNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PStatement pstatementNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonorNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PStatement pstatementNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonorNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PStatement pstatementNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonorNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList3.get(0);
        tidNode3 = (TId)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssignStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignminStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssignminStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssigndivStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssigndivStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AListStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AListStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new AAssertStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new AAssertStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        PCommaExp pcommaexpNode3;
        pcommaexpNode3 = (PCommaExp)nodeArrayList3.get(0);
	if(pcommaexpNode3 != null)
	{
	  listNode4.add(pcommaexpNode3);
	}
        }

        pstatementNode1 = new AAssertStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        PCommaExp pcommaexpNode3;
        pcommaexpNode3 = (PCommaExp)nodeArrayList4.get(0);
	if(pcommaexpNode3 != null)
	{
	  listNode4.add(pcommaexpNode3);
	}
        }

        pstatementNode1 = new AAssertStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFuncStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFuncStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AModExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultmultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AListexpExpression(tidNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TOpen topenNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        topenNode2 = (TOpen)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList5.get(0);

        pexpressionNode1 = new AOpenExpression(topenNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TLBr tlbrNode2;
        PExpression pexpressionNode3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tlbrNode2 = (TLBr)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AListConExpression(tlbrNode2, pexpressionNode3, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TLBr tlbrNode2;
        PExpression pexpressionNode3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tlbrNode2 = (TLBr)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pexpressionNode1 = new AListConExpression(tlbrNode2, pexpressionNode3, listNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncCallExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList3.get(0);

        pexpressionNode1 = new ATypeExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMaxExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMinExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AParExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaV pcommavNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pcommavNode1 = new ACommaV(pvalueNode2);
        }
	nodeList.add(pcommavNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        pcomparisonorNode1 = (PComparisonOr)nodeArrayList1.get(0);
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PComparisonOr pcomparisonorNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList1.get(0);
        pcomparisonorNode3 = (PComparisonOr)nodeArrayList3.get(0);

        pcomparisonorNode1 = new AOrComparisonOr(pcomparisonorNode2, pcomparisonorNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        pcomparisonorNode1 = (PComparisonOr)nodeArrayList1.get(0);
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PComparisonOr pcomparisonorNode2;
        PComparisonOr pcomparisonorNode3;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList1.get(0);
        pcomparisonorNode3 = (PComparisonOr)nodeArrayList3.get(0);

        pcomparisonorNode1 = new AAndComparisonOr(pcomparisonorNode2, pcomparisonorNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        pcomparisonorNode1 = (PComparisonOr)nodeArrayList1.get(0);
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PComparisonOr pcomparisonorNode2;
        pcomparisonorNode2 = (PComparisonOr)nodeArrayList2.get(0);

        pcomparisonorNode1 = new ANotComparisonOr(pcomparisonorNode2);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {

        pcomparisonorNode1 = new ATrueComparisonOr();
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {

        pcomparisonorNode1 = new AFalseComparisonOr();
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new ALessComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new AGreatComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new AGeqComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new ALeqComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new ANeqComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonOr pcomparisonorNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonorNode1 = new AEqComparisonOr(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonorNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pfunctioncallNode1 = new AFunctionCall(tidNode2, listNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        PArglist parglistNode3;
        parglistNode3 = (PArglist)nodeArrayList3.get(0);
	if(parglistNode3 != null)
	{
	  listNode4.add(parglistNode3);
	}
        }

        pfunctioncallNode1 = new AFunctionCall(tidNode2, listNode4);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaExp pcommaexpNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pcommaexpNode1 = new ACommaExp(pexpressionNode2);
        }
	nodeList.add(pcommaexpNode1);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TId tidNode2;
        PFunctionCall pfunctioncallNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList3.get(0);

        pvalueNode1 = new AMethodValue(tidNode2, pfunctioncallNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumValue(tnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNone tnoneNode2;
        tnoneNode2 = (TNone)nodeArrayList1.get(0);

        pvalueNode1 = new ANoneValue(tnoneNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new85()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new86()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaAssign pcommaassignNode1;
        pcommaassignNode1 = (PCommaAssign)nodeArrayList1.get(0);
	if(pcommaassignNode1 != null)
	{
	  listNode2.add(pcommaassignNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new87()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaAssign pcommaassignNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommaassignNode2 = (PCommaAssign)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommaassignNode2 != null)
	{
	  listNode3.add(pcommaassignNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new88()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new89()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new90()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaExp pcommaexpNode1;
        pcommaexpNode1 = (PCommaExp)nodeArrayList1.get(0);
	if(pcommaexpNode1 != null)
	{
	  listNode2.add(pcommaexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new91()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaExp pcommaexpNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommaexpNode2 = (PCommaExp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommaexpNode2 != null)
	{
	  listNode3.add(pcommaexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new92()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaV pcommavNode1;
        pcommavNode1 = (PCommaV)nodeArrayList1.get(0);
	if(pcommavNode1 != null)
	{
	  listNode2.add(pcommavNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new93()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaV pcommavNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommavNode2 = (PCommaV)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommavNode2 != null)
	{
	  listNode3.add(pcommavNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 1}, {42, SHIFT, 17}, },
			{{-1, REDUCE, 88}, },
			{{-1, ERROR, 3}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 4}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 5}, {42, SHIFT, 43}, },
			{{-1, ERROR, 6}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 7}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 8}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 9}, {1, SHIFT, 47}, {4, SHIFT, 48}, {13, SHIFT, 49}, {14, SHIFT, 50}, {15, SHIFT, 51}, },
			{{-1, ERROR, 10}, {44, ACCEPT, -1}, },
			{{-1, REDUCE, 84}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 16}, {6, SHIFT, 53}, {7, SHIFT, 54}, {8, SHIFT, 55}, {9, SHIFT, 56}, {11, SHIFT, 57}, {12, SHIFT, 58}, {17, SHIFT, 59}, {42, SHIFT, 60}, },
			{{-1, ERROR, 17}, {1, SHIFT, 62}, },
			{{-1, ERROR, 18}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 19}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 20}, {1, SHIFT, 65}, },
			{{-1, ERROR, 21}, {1, SHIFT, 66}, },
			{{-1, ERROR, 22}, {1, SHIFT, 67}, },
			{{-1, ERROR, 23}, {1, SHIFT, 68}, },
			{{-1, ERROR, 24}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 68}, },
			{{-1, REDUCE, 83}, },
			{{-1, REDUCE, 81}, },
			{{-1, REDUCE, 55}, {1, SHIFT, 47}, {15, SHIFT, 70}, {39, SHIFT, 71}, },
			{{-1, REDUCE, 82}, },
			{{-1, ERROR, 31}, {31, SHIFT, 72}, {32, SHIFT, 73}, {33, SHIFT, 74}, {34, SHIFT, 75}, {35, SHIFT, 76}, {36, SHIFT, 77}, },
			{{-1, REDUCE, 39}, {18, SHIFT, 78}, {19, SHIFT, 79}, },
			{{-1, REDUCE, 42}, {20, SHIFT, 80}, {22, SHIFT, 81}, {23, SHIFT, 82}, },
			{{-1, REDUCE, 46}, {21, SHIFT, 83}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 36}, {3, SHIFT, 84}, {29, SHIFT, 85}, },
			{{-1, REDUCE, 61}, {28, SHIFT, 86}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 54}, },
			{{-1, ERROR, 42}, {3, SHIFT, 87}, {29, SHIFT, 85}, },
			{{-1, ERROR, 43}, {10, SHIFT, 88}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 21}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 33}, {5, SHIFT, 89}, },
			{{-1, ERROR, 47}, {1, SHIFT, 18}, {2, SHIFT, 93}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 48}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 49}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 50}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 51}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 85}, },
			{{-1, REDUCE, 89}, },
			{{-1, ERROR, 54}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 55}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 56}, {42, SHIFT, 102}, },
			{{-1, ERROR, 57}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 58}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 59}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 60}, {1, SHIFT, 47}, {4, SHIFT, 106}, {13, SHIFT, 107}, {14, SHIFT, 108}, {15, SHIFT, 109}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 62}, {2, SHIFT, 110}, {42, SHIFT, 111}, },
			{{-1, ERROR, 63}, {2, SHIFT, 113}, },
			{{-1, ERROR, 64}, {5, SHIFT, 89}, {16, SHIFT, 114}, },
			{{-1, ERROR, 65}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 66}, {42, SHIFT, 117}, },
			{{-1, ERROR, 67}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 118}, {43, SHIFT, 30}, },
			{{-1, ERROR, 68}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 118}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 70}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 71}, {42, SHIFT, 122}, },
			{{-1, ERROR, 72}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 73}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 74}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 75}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 76}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 77}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 78}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 79}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 80}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 81}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 82}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 83}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 84}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 85}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 86}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {30, SHIFT, 24}, {37, SHIFT, 25}, {38, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 87}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 88}, {42, SHIFT, 140}, },
			{{-1, ERROR, 89}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 90}, },
			{{-1, REDUCE, 23}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 77}, {5, SHIFT, 89}, },
			{{-1, ERROR, 95}, {2, SHIFT, 144}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 99}, {16, SHIFT, 145}, },
			{{-1, ERROR, 100}, {3, SHIFT, 146}, {29, SHIFT, 85}, },
			{{-1, ERROR, 101}, {3, SHIFT, 147}, {29, SHIFT, 85}, },
			{{-1, ERROR, 102}, {10, SHIFT, 148}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 22}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 34}, {5, SHIFT, 89}, },
			{{-1, ERROR, 106}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 107}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 108}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 109}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 110}, {3, SHIFT, 155}, },
			{{-1, REDUCE, 6}, {4, SHIFT, 156}, {5, SHIFT, 157}, },
			{{-1, ERROR, 112}, {2, SHIFT, 161}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 51}, },
			{{-1, ERROR, 115}, {5, SHIFT, 89}, {16, SHIFT, 162}, },
			{{-1, ERROR, 116}, {5, SHIFT, 163}, },
			{{-1, ERROR, 117}, {2, SHIFT, 164}, },
			{{-1, ERROR, 118}, {39, SHIFT, 71}, },
			{{-1, ERROR, 119}, {5, SHIFT, 165}, },
			{{-1, ERROR, 120}, {5, SHIFT, 165}, },
			{{-1, ERROR, 121}, {16, SHIFT, 169}, },
			{{-1, ERROR, 122}, {1, SHIFT, 47}, },
			{{-1, REDUCE, 80}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 74}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 62}, {28, SHIFT, 86}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 140}, {3, SHIFT, 170}, },
			{{-1, REDUCE, 79}, },
			{{-1, REDUCE, 91}, },
			{{-1, REDUCE, 78}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 76}, },
			{{-1, ERROR, 145}, {4, SHIFT, 171}, },
			{{-1, ERROR, 146}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 147}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 148}, {42, SHIFT, 174}, },
			{{-1, REDUCE, 24}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 154}, {16, SHIFT, 175}, },
			{{-1, ERROR, 155}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 156}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 118}, {43, SHIFT, 30}, },
			{{-1, ERROR, 157}, {42, SHIFT, 178}, },
			{{-1, REDUCE, 86}, },
			{{-1, REDUCE, 7}, {5, SHIFT, 157}, },
			{{-1, REDUCE, 8}, {5, SHIFT, 157}, },
			{{-1, ERROR, 161}, {3, SHIFT, 181}, },
			{{-1, REDUCE, 52}, },
			{{-1, ERROR, 163}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 56}, },
			{{-1, ERROR, 165}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 118}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 92}, },
			{{-1, ERROR, 167}, {2, SHIFT, 184}, {5, SHIFT, 165}, },
			{{-1, ERROR, 168}, {2, SHIFT, 186}, {5, SHIFT, 165}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 170}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 171}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 174}, {3, SHIFT, 189}, },
			{{-1, ERROR, 175}, {4, SHIFT, 190}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 10}, {4, SHIFT, 156}, },
			{{-1, REDUCE, 9}, {5, SHIFT, 157}, },
			{{-1, REDUCE, 87}, },
			{{-1, ERROR, 181}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 182}, {2, SHIFT, 193}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 93}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 189}, {6, SHIFT, 2}, {7, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {17, SHIFT, 8}, {42, SHIFT, 9}, },
			{{-1, ERROR, 190}, {1, SHIFT, 18}, {15, SHIFT, 19}, {24, SHIFT, 20}, {25, SHIFT, 21}, {26, SHIFT, 22}, {27, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 32}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {15, 52}, },
			{{-1, 12}, },
			{{-1, 112}, },
			{{-1, 158}, {160, 180}, {179, 180}, },
			{{-1, 159}, {178, 191}, },
			{{-1, 13}, {84, 136}, {87, 139}, {146, 172}, {147, 173}, {155, 176}, {170, 187}, {181, 192}, {189, 194}, },
			{{-1, 31}, {6, 44}, {7, 45}, {8, 46}, {18, 63}, {19, 64}, {47, 94}, {48, 96}, {49, 97}, {50, 98}, {51, 99}, {57, 103}, {58, 104}, {59, 105}, {65, 116}, {70, 121}, {72, 124}, {73, 125}, {74, 126}, {75, 127}, {76, 128}, {77, 129}, {78, 130}, {79, 131}, {89, 141}, {106, 151}, {107, 152}, {108, 153}, {109, 154}, {163, 182}, {171, 188}, {190, 195}, },
			{{-1, 32}, {80, 132}, {81, 133}, {82, 134}, },
			{{-1, 33}, {83, 135}, },
			{{-1, 34}, },
			{{-1, 35}, },
			{{-1, 166}, {167, 185}, {168, 185}, },
			{{-1, 36}, {4, 42}, {54, 100}, {55, 101}, },
			{{-1, 37}, {85, 137}, },
			{{-1, 38}, {24, 69}, {86, 138}, },
			{{-1, 39}, },
			{{-1, 40}, {0, 14}, {15, 14}, {16, 61}, {71, 123}, {84, 14}, {87, 14}, {146, 14}, {147, 14}, {155, 14}, {170, 14}, {181, 14}, {189, 14}, },
			{{-1, 95}, },
			{{-1, 90}, {46, 92}, {91, 142}, {105, 150}, {115, 142}, {143, 142}, {149, 142}, },
			{{-1, 41}, {67, 119}, {68, 120}, {156, 177}, {165, 183}, },
			{{-1, 15}, },
			{{-1, 160}, {159, 179}, },
			{{-1, 16}, },
			{{-1, 91}, {64, 115}, {94, 143}, {104, 149}, },
			{{-1, 167}, {120, 168}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'def', tab, 'if', 'while', 'for', 'return', 'print', 'assert', id, EOF",
			"expecting: id",
			"expecting: tab, 'if', 'while', 'for', 'return', 'print', 'assert', id",
			"expecting: '(', '[', 'open', 'type', 'max', 'min', 'not', 'true', 'false', 'None', number, id, string",
			"expecting: '(', '[', 'open', 'type', 'max', 'min', 'None', number, id, string",
			"expecting: '(', '=', '-=', '/=', '['",
			"expecting: EOF",
			"expecting: '('",
			"expecting: ':', 'and', 'or'",
			"expecting: 'def', ')', ':', ',', tab, 'if', 'while', 'for', 'return', 'print', ']', 'assert', '+', '-', '*', '**', '/', '%', 'and', 'or', '<', '>', '>=', '<=', '==', '!=', id, EOF",
			"expecting: 'def', '(', ')', ':', ',', tab, 'if', 'while', 'for', 'return', 'print', '[', ']', 'assert', '+', '-', '*', '**', '/', '%', 'and', 'or', '<', '>', '>=', '<=', '==', '!=', '.', id, EOF",
			"expecting: '<', '>', '>=', '<=', '==', '!='",
			"expecting: 'def', ')', ':', ',', tab, 'if', 'while', 'for', 'return', 'print', ']', 'assert', '+', '-', 'and', 'or', '<', '>', '>=', '<=', '==', '!=', id, EOF",
			"expecting: 'def', ')', ':', ',', tab, 'if', 'while', 'for', 'return', 'print', ']', 'assert', '+', '-', '*', '/', '%', 'and', 'or', '<', '>', '>=', '<=', '==', '!=', id, EOF",
			"expecting: ':', 'or'",
			"expecting: 'in'",
			"expecting: 'def', ',', tab, 'if', 'while', 'for', 'return', 'print', 'assert', id, EOF",
			"expecting: '(', ')', '[', 'open', 'type', 'max', 'min', 'None', number, id, string",
			"expecting: ')', id",
			"expecting: ')'",
			"expecting: ',', ']'",
			"expecting: 'None', number, id, string",
			"expecting: 'def', ')', ',', tab, 'if', 'while', 'for', 'return', 'print', ']', 'assert', id, EOF",
			"expecting: ')', ','",
			"expecting: ']'",
			"expecting: ':'",
			"expecting: ')', '=', ','",
			"expecting: ','",
			"expecting: '.'",
			"expecting: 'def', ')', ':', ',', tab, 'if', 'while', 'for', 'return', 'print', ']', 'assert', 'and', 'or', '<', '>', '>=', '<=', '==', '!=', id, EOF",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 1, 4, 4, 4, 5, 6, 0, 0, 0, 0, 0, 2, 7, 4, 4, 7, 7, 7, 7, 3, 8, 8, 9, 9, 10, 9, 11, 12, 13, 9, 9, 14, 8, 8, 8, 9, 9, 14, 15, 0, 16, 16, 17, 4, 4, 4, 4, 0, 2, 3, 3, 1, 4, 4, 4, 5, 0, 18, 19, 20, 4, 1, 21, 21, 8, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 3, 3, 2, 1, 4, 22, 16, 0, 9, 23, 19, 0, 0, 0, 24, 14, 14, 15, 0, 16, 16, 4, 4, 4, 4, 25, 26, 19, 9, 9, 20, 27, 19, 28, 27, 27, 24, 7, 9, 8, 8, 8, 8, 8, 8, 29, 29, 12, 12, 12, 13, 0, 8, 8, 0, 25, 22, 22, 23, 9, 30, 2, 2, 1, 16, 0, 0, 0, 0, 24, 2, 21, 1, 23, 23, 23, 25, 9, 4, 9, 21, 23, 23, 23, 9, 2, 4, 0, 0, 25, 30, 0, 23, 26, 23, 23, 2, 19, 23, 9, 23, 9, 0, 0, 2, 4, 23, 0, 9, 0, 0, 
        };*/
}
