/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.analysis;

import java.util.*;
import minipython.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(Node node)
    {
    }

    public void defaultOut(Node node)
    {
    }

    public void caseStart(Start node)
    {
        inStart(node);
        node.getPGoal().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAGoal(AGoal node)
    {
        defaultIn(node);
    }

    public void outAGoal(AGoal node)
    {
        defaultOut(node);
    }

    public void caseAGoal(AGoal node)
    {
        inAGoal(node);
        {
            Object temp[] = node.getCommands().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommands) temp[i]).apply(this);
            }
        }
        outAGoal(node);
    }

    public void inAFunCommands(AFunCommands node)
    {
        defaultIn(node);
    }

    public void outAFunCommands(AFunCommands node)
    {
        defaultOut(node);
    }

    public void caseAFunCommands(AFunCommands node)
    {
        inAFunCommands(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAFunCommands(node);
    }

    public void inAStatCommands(AStatCommands node)
    {
        defaultIn(node);
    }

    public void outAStatCommands(AStatCommands node)
    {
        defaultOut(node);
    }

    public void caseAStatCommands(AStatCommands node)
    {
        inAStatCommands(node);
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAStatCommands(node);
    }

    public void inAFunction(AFunction node)
    {
        defaultIn(node);
    }

    public void outAFunction(AFunction node)
    {
        defaultOut(node);
    }

    public void caseAFunction(AFunction node)
    {
        inAFunction(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        {
            Object temp[] = node.getArgument().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PArgument) temp[i]).apply(this);
            }
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAFunction(node);
    }

    public void inAArgument(AArgument node)
    {
        defaultIn(node);
    }

    public void outAArgument(AArgument node)
    {
        defaultOut(node);
    }

    public void caseAArgument(AArgument node)
    {
        inAArgument(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        {
            Object temp[] = node.getAssignV().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PAssignV) temp[i]).apply(this);
            }
        }
        {
            Object temp[] = node.getCommaAssign().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaAssign) temp[i]).apply(this);
            }
        }
        outAArgument(node);
    }

    public void inACommaAssign(ACommaAssign node)
    {
        defaultIn(node);
    }

    public void outACommaAssign(ACommaAssign node)
    {
        defaultOut(node);
    }

    public void caseACommaAssign(ACommaAssign node)
    {
        inACommaAssign(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        {
            Object temp[] = node.getAssignV().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PAssignV) temp[i]).apply(this);
            }
        }
        outACommaAssign(node);
    }

    public void inAAssignV(AAssignV node)
    {
        defaultIn(node);
    }

    public void outAAssignV(AAssignV node)
    {
        defaultOut(node);
    }

    public void caseAAssignV(AAssignV node)
    {
        inAAssignV(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAAssignV(node);
    }

    public void inAIfStatement(AIfStatement node)
    {
        defaultIn(node);
    }

    public void outAIfStatement(AIfStatement node)
    {
        defaultOut(node);
    }

    public void caseAIfStatement(AIfStatement node)
    {
        inAIfStatement(node);
        if(node.getComparisonOr() != null)
        {
            node.getComparisonOr().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAIfStatement(node);
    }

    public void inAWhileStatement(AWhileStatement node)
    {
        defaultIn(node);
    }

    public void outAWhileStatement(AWhileStatement node)
    {
        defaultOut(node);
    }

    public void caseAWhileStatement(AWhileStatement node)
    {
        inAWhileStatement(node);
        if(node.getComparisonOr() != null)
        {
            node.getComparisonOr().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAWhileStatement(node);
    }

    public void inAForStatement(AForStatement node)
    {
        defaultIn(node);
    }

    public void outAForStatement(AForStatement node)
    {
        defaultOut(node);
    }

    public void caseAForStatement(AForStatement node)
    {
        inAForStatement(node);
        if(node.getForid() != null)
        {
            node.getForid().apply(this);
        }
        if(node.getInid() != null)
        {
            node.getInid().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAForStatement(node);
    }

    public void inAReturnStatement(AReturnStatement node)
    {
        defaultIn(node);
    }

    public void outAReturnStatement(AReturnStatement node)
    {
        defaultOut(node);
    }

    public void caseAReturnStatement(AReturnStatement node)
    {
        inAReturnStatement(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAReturnStatement(node);
    }

    public void inAPrintStatement(APrintStatement node)
    {
        defaultIn(node);
    }

    public void outAPrintStatement(APrintStatement node)
    {
        defaultOut(node);
    }

    public void caseAPrintStatement(APrintStatement node)
    {
        inAPrintStatement(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        {
            Object temp[] = node.getCommaExp().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaExp) temp[i]).apply(this);
            }
        }
        outAPrintStatement(node);
    }

    public void inAAssignStatement(AAssignStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignStatement(AAssignStatement node)
    {
        defaultOut(node);
    }

    public void caseAAssignStatement(AAssignStatement node)
    {
        inAAssignStatement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAssignStatement(node);
    }

    public void inAAssignminStatement(AAssignminStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignminStatement(AAssignminStatement node)
    {
        defaultOut(node);
    }

    public void caseAAssignminStatement(AAssignminStatement node)
    {
        inAAssignminStatement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAssignminStatement(node);
    }

    public void inAAssigndivStatement(AAssigndivStatement node)
    {
        defaultIn(node);
    }

    public void outAAssigndivStatement(AAssigndivStatement node)
    {
        defaultOut(node);
    }

    public void caseAAssigndivStatement(AAssigndivStatement node)
    {
        inAAssigndivStatement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAssigndivStatement(node);
    }

    public void inAListStatement(AListStatement node)
    {
        defaultIn(node);
    }

    public void outAListStatement(AListStatement node)
    {
        defaultOut(node);
    }

    public void caseAListStatement(AListStatement node)
    {
        inAListStatement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getLbr() != null)
        {
            node.getLbr().apply(this);
        }
        if(node.getRbr() != null)
        {
            node.getRbr().apply(this);
        }
        outAListStatement(node);
    }

    public void inAAssertStatement(AAssertStatement node)
    {
        defaultIn(node);
    }

    public void outAAssertStatement(AAssertStatement node)
    {
        defaultOut(node);
    }

    public void caseAAssertStatement(AAssertStatement node)
    {
        inAAssertStatement(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        {
            Object temp[] = node.getCommaExp().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaExp) temp[i]).apply(this);
            }
        }
        outAAssertStatement(node);
    }

    public void inAFuncStatement(AFuncStatement node)
    {
        defaultIn(node);
    }

    public void outAFuncStatement(AFuncStatement node)
    {
        defaultOut(node);
    }

    public void caseAFuncStatement(AFuncStatement node)
    {
        inAFuncStatement(node);
        if(node.getFunctionCall() != null)
        {
            node.getFunctionCall().apply(this);
        }
        outAFuncStatement(node);
    }

    public void inAMinusExpression(AMinusExpression node)
    {
        defaultIn(node);
    }

    public void outAMinusExpression(AMinusExpression node)
    {
        defaultOut(node);
    }

    public void caseAMinusExpression(AMinusExpression node)
    {
        inAMinusExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAMinusExpression(node);
    }

    public void inAAddExpression(AAddExpression node)
    {
        defaultIn(node);
    }

    public void outAAddExpression(AAddExpression node)
    {
        defaultOut(node);
    }

    public void caseAAddExpression(AAddExpression node)
    {
        inAAddExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAAddExpression(node);
    }

    public void inAModExpression(AModExpression node)
    {
        defaultIn(node);
    }

    public void outAModExpression(AModExpression node)
    {
        defaultOut(node);
    }

    public void caseAModExpression(AModExpression node)
    {
        inAModExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAModExpression(node);
    }

    public void inADivExpression(ADivExpression node)
    {
        defaultIn(node);
    }

    public void outADivExpression(ADivExpression node)
    {
        defaultOut(node);
    }

    public void caseADivExpression(ADivExpression node)
    {
        inADivExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outADivExpression(node);
    }

    public void inAMultExpression(AMultExpression node)
    {
        defaultIn(node);
    }

    public void outAMultExpression(AMultExpression node)
    {
        defaultOut(node);
    }

    public void caseAMultExpression(AMultExpression node)
    {
        inAMultExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAMultExpression(node);
    }

    public void inAMultmultExpression(AMultmultExpression node)
    {
        defaultIn(node);
    }

    public void outAMultmultExpression(AMultmultExpression node)
    {
        defaultOut(node);
    }

    public void caseAMultmultExpression(AMultmultExpression node)
    {
        inAMultmultExpression(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAMultmultExpression(node);
    }

    public void inAFuncCallExpression(AFuncCallExpression node)
    {
        defaultIn(node);
    }

    public void outAFuncCallExpression(AFuncCallExpression node)
    {
        defaultOut(node);
    }

    public void caseAFuncCallExpression(AFuncCallExpression node)
    {
        inAFuncCallExpression(node);
        if(node.getFunctionCall() != null)
        {
            node.getFunctionCall().apply(this);
        }
        outAFuncCallExpression(node);
    }

    public void inAValueExpression(AValueExpression node)
    {
        defaultIn(node);
    }

    public void outAValueExpression(AValueExpression node)
    {
        defaultOut(node);
    }

    public void caseAValueExpression(AValueExpression node)
    {
        inAValueExpression(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAValueExpression(node);
    }

    public void inAIdExpression(AIdExpression node)
    {
        defaultIn(node);
    }

    public void outAIdExpression(AIdExpression node)
    {
        defaultOut(node);
    }

    public void caseAIdExpression(AIdExpression node)
    {
        inAIdExpression(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdExpression(node);
    }

    public void inATypeExpression(ATypeExpression node)
    {
        defaultIn(node);
    }

    public void outATypeExpression(ATypeExpression node)
    {
        defaultOut(node);
    }

    public void caseATypeExpression(ATypeExpression node)
    {
        inATypeExpression(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outATypeExpression(node);
    }

    public void inAMaxExpression(AMaxExpression node)
    {
        defaultIn(node);
    }

    public void outAMaxExpression(AMaxExpression node)
    {
        defaultOut(node);
    }

    public void caseAMaxExpression(AMaxExpression node)
    {
        inAMaxExpression(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        {
            Object temp[] = node.getCommaV().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaV) temp[i]).apply(this);
            }
        }
        outAMaxExpression(node);
    }

    public void inAMinExpression(AMinExpression node)
    {
        defaultIn(node);
    }

    public void outAMinExpression(AMinExpression node)
    {
        defaultOut(node);
    }

    public void caseAMinExpression(AMinExpression node)
    {
        inAMinExpression(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        {
            Object temp[] = node.getCommaV().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaV) temp[i]).apply(this);
            }
        }
        outAMinExpression(node);
    }

    public void inAParExpression(AParExpression node)
    {
        defaultIn(node);
    }

    public void outAParExpression(AParExpression node)
    {
        defaultOut(node);
    }

    public void caseAParExpression(AParExpression node)
    {
        inAParExpression(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAParExpression(node);
    }

    public void inAListexpExpression(AListexpExpression node)
    {
        defaultIn(node);
    }

    public void outAListexpExpression(AListexpExpression node)
    {
        defaultOut(node);
    }

    public void caseAListexpExpression(AListexpExpression node)
    {
        inAListexpExpression(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAListexpExpression(node);
    }

    public void inAOpenExpression(AOpenExpression node)
    {
        defaultIn(node);
    }

    public void outAOpenExpression(AOpenExpression node)
    {
        defaultOut(node);
    }

    public void caseAOpenExpression(AOpenExpression node)
    {
        inAOpenExpression(node);
        if(node.getOpen() != null)
        {
            node.getOpen().apply(this);
        }
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAOpenExpression(node);
    }

    public void inAListConExpression(AListConExpression node)
    {
        defaultIn(node);
    }

    public void outAListConExpression(AListConExpression node)
    {
        defaultOut(node);
    }

    public void caseAListConExpression(AListConExpression node)
    {
        inAListConExpression(node);
        if(node.getLBr() != null)
        {
            node.getLBr().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        {
            Object temp[] = node.getCommaExp().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaExp) temp[i]).apply(this);
            }
        }
        outAListConExpression(node);
    }

    public void inACommaV(ACommaV node)
    {
        defaultIn(node);
    }

    public void outACommaV(ACommaV node)
    {
        defaultOut(node);
    }

    public void caseACommaV(ACommaV node)
    {
        inACommaV(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outACommaV(node);
    }

    public void inAOrComparisonOr(AOrComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAOrComparisonOr(AOrComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAOrComparisonOr(AOrComparisonOr node)
    {
        inAOrComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAOrComparisonOr(node);
    }

    public void inAAndComparisonOr(AAndComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAAndComparisonOr(AAndComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAAndComparisonOr(AAndComparisonOr node)
    {
        inAAndComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAAndComparisonOr(node);
    }

    public void inANotComparisonOr(ANotComparisonOr node)
    {
        defaultIn(node);
    }

    public void outANotComparisonOr(ANotComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseANotComparisonOr(ANotComparisonOr node)
    {
        inANotComparisonOr(node);
        if(node.getComparisonOr() != null)
        {
            node.getComparisonOr().apply(this);
        }
        outANotComparisonOr(node);
    }

    public void inATrueComparisonOr(ATrueComparisonOr node)
    {
        defaultIn(node);
    }

    public void outATrueComparisonOr(ATrueComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseATrueComparisonOr(ATrueComparisonOr node)
    {
        inATrueComparisonOr(node);
        outATrueComparisonOr(node);
    }

    public void inAFalseComparisonOr(AFalseComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAFalseComparisonOr(AFalseComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAFalseComparisonOr(AFalseComparisonOr node)
    {
        inAFalseComparisonOr(node);
        outAFalseComparisonOr(node);
    }

    public void inALessComparisonOr(ALessComparisonOr node)
    {
        defaultIn(node);
    }

    public void outALessComparisonOr(ALessComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseALessComparisonOr(ALessComparisonOr node)
    {
        inALessComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outALessComparisonOr(node);
    }

    public void inAGreatComparisonOr(AGreatComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAGreatComparisonOr(AGreatComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAGreatComparisonOr(AGreatComparisonOr node)
    {
        inAGreatComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAGreatComparisonOr(node);
    }

    public void inAGeqComparisonOr(AGeqComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAGeqComparisonOr(AGeqComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAGeqComparisonOr(AGeqComparisonOr node)
    {
        inAGeqComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAGeqComparisonOr(node);
    }

    public void inALeqComparisonOr(ALeqComparisonOr node)
    {
        defaultIn(node);
    }

    public void outALeqComparisonOr(ALeqComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseALeqComparisonOr(ALeqComparisonOr node)
    {
        inALeqComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outALeqComparisonOr(node);
    }

    public void inANeqComparisonOr(ANeqComparisonOr node)
    {
        defaultIn(node);
    }

    public void outANeqComparisonOr(ANeqComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseANeqComparisonOr(ANeqComparisonOr node)
    {
        inANeqComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outANeqComparisonOr(node);
    }

    public void inAEqComparisonOr(AEqComparisonOr node)
    {
        defaultIn(node);
    }

    public void outAEqComparisonOr(AEqComparisonOr node)
    {
        defaultOut(node);
    }

    public void caseAEqComparisonOr(AEqComparisonOr node)
    {
        inAEqComparisonOr(node);
        if(node.getLpar() != null)
        {
            node.getLpar().apply(this);
        }
        if(node.getRpar() != null)
        {
            node.getRpar().apply(this);
        }
        outAEqComparisonOr(node);
    }

    public void inAFunctionCall(AFunctionCall node)
    {
        defaultIn(node);
    }

    public void outAFunctionCall(AFunctionCall node)
    {
        defaultOut(node);
    }

    public void caseAFunctionCall(AFunctionCall node)
    {
        inAFunctionCall(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        {
            Object temp[] = node.getArglist().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PArglist) temp[i]).apply(this);
            }
        }
        outAFunctionCall(node);
    }

    public void inAArglist(AArglist node)
    {
        defaultIn(node);
    }

    public void outAArglist(AArglist node)
    {
        defaultOut(node);
    }

    public void caseAArglist(AArglist node)
    {
        inAArglist(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        {
            Object temp[] = node.getCommaExp().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PCommaExp) temp[i]).apply(this);
            }
        }
        outAArglist(node);
    }

    public void inACommaExp(ACommaExp node)
    {
        defaultIn(node);
    }

    public void outACommaExp(ACommaExp node)
    {
        defaultOut(node);
    }

    public void caseACommaExp(ACommaExp node)
    {
        inACommaExp(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outACommaExp(node);
    }

    public void inAMethodValue(AMethodValue node)
    {
        defaultIn(node);
    }

    public void outAMethodValue(AMethodValue node)
    {
        defaultOut(node);
    }

    public void caseAMethodValue(AMethodValue node)
    {
        inAMethodValue(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getFunctionCall() != null)
        {
            node.getFunctionCall().apply(this);
        }
        outAMethodValue(node);
    }

    public void inANumValue(ANumValue node)
    {
        defaultIn(node);
    }

    public void outANumValue(ANumValue node)
    {
        defaultOut(node);
    }

    public void caseANumValue(ANumValue node)
    {
        inANumValue(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumValue(node);
    }

    public void inAStringValue(AStringValue node)
    {
        defaultIn(node);
    }

    public void outAStringValue(AStringValue node)
    {
        defaultOut(node);
    }

    public void caseAStringValue(AStringValue node)
    {
        inAStringValue(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValue(node);
    }

    public void inANoneValue(ANoneValue node)
    {
        defaultIn(node);
    }

    public void outANoneValue(ANoneValue node)
    {
        defaultOut(node);
    }

    public void caseANoneValue(ANoneValue node)
    {
        inANoneValue(node);
        if(node.getNone() != null)
        {
            node.getNone().apply(this);
        }
        outANoneValue(node);
    }
}
