/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.lexer;

import java.io.*;
import java.util.*;
import minipython.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TDef(line, pos); }
    Token new1(int line, int pos) { return new TLPar(line, pos); }
    Token new2(int line, int pos) { return new TRPar(line, pos); }
    Token new3(int line, int pos) { return new TSemi(line, pos); }
    Token new4(int line, int pos) { return new TAssign(line, pos); }
    Token new5(int line, int pos) { return new TComma(line, pos); }
    Token new6(String text, int line, int pos) { return new TTab(text, line, pos); }
    Token new7(int line, int pos) { return new TIf(line, pos); }
    Token new8(int line, int pos) { return new TWhile(line, pos); }
    Token new9(int line, int pos) { return new TFor(line, pos); }
    Token new10(int line, int pos) { return new TIn(line, pos); }
    Token new11(int line, int pos) { return new TReturn(line, pos); }
    Token new12(int line, int pos) { return new TPrint(line, pos); }
    Token new13(int line, int pos) { return new TAssignMinus(line, pos); }
    Token new14(int line, int pos) { return new TAssignDiv(line, pos); }
    Token new15(int line, int pos) { return new TLBr(line, pos); }
    Token new16(int line, int pos) { return new TRBr(line, pos); }
    Token new17(int line, int pos) { return new TAssert(line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TMultmult(line, pos); }
    Token new22(int line, int pos) { return new TDiv(line, pos); }
    Token new23(int line, int pos) { return new TMod(line, pos); }
    Token new24(int line, int pos) { return new TOpen(line, pos); }
    Token new25(int line, int pos) { return new TType(line, pos); }
    Token new26(int line, int pos) { return new TMax(line, pos); }
    Token new27(int line, int pos) { return new TMin(line, pos); }
    Token new28(int line, int pos) { return new TAnd(line, pos); }
    Token new29(int line, int pos) { return new TOr(line, pos); }
    Token new30(int line, int pos) { return new TNot(line, pos); }
    Token new31(int line, int pos) { return new TLess(line, pos); }
    Token new32(int line, int pos) { return new TGreat(line, pos); }
    Token new33(int line, int pos) { return new TGeq(line, pos); }
    Token new34(int line, int pos) { return new TLeq(line, pos); }
    Token new35(int line, int pos) { return new TEq(line, pos); }
    Token new36(int line, int pos) { return new TNeq(line, pos); }
    Token new37(int line, int pos) { return new TTrue(line, pos); }
    Token new38(int line, int pos) { return new TFalse(line, pos); }
    Token new39(int line, int pos) { return new TDot(line, pos); }
    Token new40(int line, int pos) { return new TNone(line, pos); }
    Token new41(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new42(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new43(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new44(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new45(String text, int line, int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {37, 37, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 57, 18}, {58, 58, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 77, 23}, {78, 78, 24}, {79, 90, 23}, {91, 91, 25}, {93, 93, 26}, {97, 97, 27}, {98, 99, 28}, {100, 100, 29}, {101, 101, 28}, {102, 102, 30}, {103, 104, 28}, {105, 105, 31}, {106, 108, 28}, {109, 109, 32}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 28}, {114, 114, 36}, {115, 115, 28}, {116, 116, 37}, {117, 118, 28}, {119, 119, 38}, {120, 122, 28}, },
            {},
            {},
            {},
            {},
            {{61, 61, 39}, },
            {{0, 9, 40}, {11, 12, 40}, {14, 33, 40}, {34, 34, 41}, {35, 127, 40}, },
            {{0, 9, 42}, {10, 10, 43}, {11, 12, 42}, {13, 13, 44}, {14, 127, 42}, },
            {},
            {{0, 9, 45}, {11, 12, 45}, {14, 38, 45}, {39, 39, 46}, {40, 127, 45}, },
            {},
            {},
            {{42, 42, 47}, },
            {},
            {},
            {{61, 61, 48}, },
            {},
            {{61, 61, 49}, },
            {{46, 46, 50}, {48, 57, 18}, },
            {},
            {{61, 61, 51}, },
            {{61, 61, 52}, },
            {{61, 61, 53}, },
            {{48, 57, 54}, {65, 90, 55}, {97, 122, 56}, },
            {{48, 90, -25}, {97, 110, 56}, {111, 111, 57}, {112, 122, 56}, },
            {},
            {},
            {{48, 90, -25}, {97, 109, 56}, {110, 110, 58}, {111, 114, 56}, {115, 115, 59}, {116, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 100, 56}, {101, 101, 60}, {102, 122, 56}, },
            {{48, 90, -25}, {97, 97, 61}, {98, 110, 56}, {111, 111, 62}, {112, 122, 56}, },
            {{48, 90, -25}, {97, 101, 56}, {102, 102, 63}, {103, 109, 56}, {110, 110, 64}, {111, 122, 56}, },
            {{48, 90, -25}, {97, 97, 65}, {98, 104, 56}, {105, 105, 66}, {106, 122, 56}, },
            {{48, 110, -26}, {111, 111, 67}, {112, 122, 56}, },
            {{48, 90, -25}, {97, 111, 56}, {112, 112, 68}, {113, 113, 56}, {114, 114, 69}, {115, 122, 56}, },
            {{48, 90, -25}, {97, 113, 56}, {114, 114, 70}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 71}, {102, 122, 56}, },
            {{48, 113, -37}, {114, 114, 72}, {115, 120, 56}, {121, 121, 73}, {122, 122, 56}, },
            {{48, 90, -25}, {97, 103, 56}, {104, 104, 74}, {105, 122, 56}, },
            {},
            {{0, 127, -8}, },
            {},
            {{0, 127, -9}, },
            {},
            {{10, 10, 75}, },
            {{0, 127, -11}, },
            {},
            {},
            {},
            {},
            {{48, 57, 76}, },
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 109, -29}, {110, 110, 77}, {111, 122, 56}, },
            {{48, 90, -25}, {97, 99, 56}, {100, 100, 78}, {101, 122, 56}, },
            {{48, 90, -25}, {97, 114, 56}, {115, 115, 79}, {116, 122, 56}, },
            {{48, 101, -33}, {102, 102, 80}, {103, 122, 56}, },
            {{48, 90, -25}, {97, 107, 56}, {108, 108, 81}, {109, 122, 56}, },
            {{48, 113, -37}, {114, 114, 82}, {115, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 119, 56}, {120, 120, 83}, {121, 122, 56}, },
            {{48, 109, -29}, {110, 110, 84}, {111, 122, 56}, },
            {{48, 90, -25}, {97, 115, 56}, {116, 116, 85}, {117, 122, 56}, },
            {{48, 100, -31}, {101, 101, 86}, {102, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 104, 56}, {105, 105, 87}, {106, 122, 56}, },
            {{48, 115, -69}, {116, 116, 88}, {117, 122, 56}, },
            {{48, 90, -25}, {97, 116, 56}, {117, 117, 89}, {118, 122, 56}, },
            {{48, 111, -36}, {112, 112, 90}, {113, 122, 56}, },
            {{48, 104, -72}, {105, 105, 91}, {106, 122, 56}, },
            {},
            {{48, 57, 76}, },
            {{48, 100, -31}, {101, 101, 92}, {102, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 100, -31}, {101, 101, 93}, {102, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 114, -61}, {115, 115, 94}, {116, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 109, -29}, {110, 110, 95}, {111, 122, 56}, },
            {{48, 109, -29}, {110, 110, 96}, {111, 122, 56}, },
            {{48, 116, -74}, {117, 117, 97}, {118, 122, 56}, },
            {{48, 100, -31}, {101, 101, 98}, {102, 122, 56}, },
            {{48, 100, -31}, {101, 101, 99}, {102, 122, 56}, },
            {{48, 107, -63}, {108, 108, 100}, {109, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 113, -37}, {114, 114, 101}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 102}, {102, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 115, -69}, {116, 116, 103}, {117, 122, 56}, },
            {{48, 113, -37}, {114, 114, 104}, {115, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 100, -31}, {101, 101, 105}, {102, 122, 56}, },
            {{48, 115, -69}, {116, 116, 106}, {117, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 109, -29}, {110, 110, 107}, {111, 122, 56}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 6, 45, 45, 45, -1, -1, -1, 23, -1, 1, 2, 20, 18, 5, 19, 39, 22, 42, 3, 31, 4, 32, 43, 43, 15, 16, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 36, -1, 44, -1, 41, 41, -1, 44, 21, 13, 14, -1, 34, 35, 33, 43, 43, 43, 43, 43, 43, 43, 43, 43, 7, 10, 43, 43, 43, 43, 29, 43, 43, 43, 43, 43, 41, 42, 43, 28, 43, 0, 43, 9, 26, 27, 30, 43, 43, 43, 43, 43, 43, 40, 43, 43, 24, 43, 43, 37, 25, 43, 43, 38, 12, 43, 8, 17, 11, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
